### ISSUE TITLE
Options `timeout` and `num-solutions` make solver return error

### ISSUE THREAD

**Issue by volisoft** [MiniZinc/minizinc-js#16]
Minimal example from the README.

```
const model = new MiniZinc.Model();
  model.addFile('test.mzn', 'var 1..3: x;');
  const solve = model.solve({
    options: {
      timeout: 10000,   # this will fail
      'num-solutions': 100,  # this will fail
      solver: 'gecode',
      'all-solutions': true
    }
  });
  solve.on('solution', solution => {
    console.log(solution.output.json);
  });
  solve.then(result => {
    console.log(result.status);
  });
```

This code fails with the following error.
```
minizinc.js:1 Uncaught {type: 'exit', code: 1}
n @ minizinc.js:1
s.onmessage @ minizinc.js:1
```

Note, the error message is absent, so it's hard to troubleshoot what exactly is failing.

**Comment by cyderize** [comment]
Hi,

Ah yes, the `timeout` is a mistake in the documentation, it should be `'time-limit': 10000`.
The other problem with `num-solutions` is a bug in the upstream MiniZInc/libminizinc built-in interface to Gecode.

I will push some fixes for these shortly.

As a workaround for now, you can use:

```js
const model = new MiniZinc.Model();
model.addFile('test.mzn', 'var 1..3: x;');
const solve = model.solve({
  options: {
    'time-limit': 10000, // timeout was a typo in the docs
    '-n': 100, // num-solutions should work in the next version of MiniZinc
    solver: 'gecode'
  }
});
solve.on('solution', solution => {
  console.log(solution.output.json);
});
solve.then(result => {
  console.log(result.status);
});
```

With regards to the lack of an error message, that's because this particular error seems to get printed to stderr rather than a proper message (I'll see if I can fix that too).

It may be useful to do

```js
solve.on('stderr', console.log);
```

So that any stderr output is visible in the browser console.

**Comment by volisoft** [comment]
Thank you for your response. I can confirm that the workaround parameters are accepted by the solver.
Output from "stderr"  is especially helpful.

Just one note, it seems like the time limit parameter is not respected. When I run complex model with short time limit (I tried a range from 5 to 10000) solver runs until completion disregarding the time limit.

**Comment by cyderize** [comment]
As far as I can tell, the time limit does seem to be respected at least by Gecode, Chuffed and HiGHS.

For example, see this playground with [`'time-limit': 5000`](https://is.gd/sspmSi).

CBC does seem like it's not actually stopping though - I'll have a look at that and see if I can figure out what's going on.

**Comment by volisoft** [comment]
Confirmed, `time-limit` is respected. There was an issue in my code. Thank you for your help!
